## Name: Ummi Aishatu Ibrahim
## Date: 28/09/2020
## Student Number: 940165

# Task 1.1

In [30]:
#2
x = 345
output = 2*x + 5
print(output)

695


In [31]:
#3
print('Hello World')

Hello World


In [32]:
#4
def f(x,w,b):
    result = w*x + b
    return result

In [33]:
print(f(345,2,5))

695


## Task 1.2

In [41]:
#1
myList = ['safy', 'amira', 'abudy','waleed']
for i in reversed(myList):
    print(i)
    

waleed
abudy
amira
safy


In [42]:
#2
def equals100(x):
    if x == 100:
        print(True)
    else:
        print(False)

In [44]:
print(equals100(100))

True
None


In [45]:
print(equals100(10))

False
None


In [48]:
#3
myDictionary = {
    'data_name' : 'myData',
    'data' : '["cat", "dog", "fish"]',
    'labels' : '[2,3,4]'
}

In [49]:
#4
print(myDictionary['data_name'])
print(myDictionary['data'])
print(myDictionary['labels'])

myData
["cat", "dog", "fish"]
[2,3,4]


## Task 1.3

In [71]:
#1
import numpy as np 

#2
X = np.random.randint(5, size = (2,3))
Y = np.random.randint(5, size = (3,4))

#3
# matrix multiplication using dot method 
# where dot(a,b)[i,j,k,m] = sum(a[i,j,:]*b[k,:,m])
Z = X.dot(Y)
print(Z)

[[16  9  7  6]
 [24 17 10  6]]


In [72]:
#4
print(Z[:1,])

[[16  9  7  6]]


## Task 1.4

In [3]:
#1
import numpy as np
import matplotlib.pyplot as mat
# load the file 
iris = np.load('Downloads/Iris_data.npy')
# query the shape 
#2
print(iris.shape)
#printed (150,4)
#3
#plot the data selecting 2 feature dimension and using the matplitlib.pyplot's scatter function
data = np.random.randn(150,4) ## 2 feature dimension
mat.figure()## create a new canvas
mat.scatter(data[:,0], data[:,1]) ## plot data as a scatter function
#4
mat.xlabel('label 1') ## x axis label
mat.ylabel('label 2') ## y axis label
mat.title('scatter plot of 2D data')

mat.show() # display plot to screen
# the 2 feature is sepal width and sepal length

FileNotFoundError: [Errno 2] No such file or directory: 'Downloads/Iris_data.npy'